### PR TITLE
make role distribution-agnostic

### PR DESCRIPTION
**Pull request by whysthatso**
i ran this against an arch linux setup, and it worked just fine.

### CODE REVIEW

**Comment by dbrennand** [comment]
Hey @whysthatso - Thanks for your contribution 🙂 

I'm just waiting on https://github.com/CarloDePieri/docker-archlinux-ansible/pull/4 to be merged, to make sure Arch Linux is tested with Molecule and then I'll merge this 👍🏻

**Review by dbrennand — APPROVED** [review]
LGTM

**Comment by dbrennand** [comment]
Thanks for your contribution @whysthatso 🙂

**Comment by whysthatso** [comment]
yey :) :excited:

**Pull request merged**
